blogTitle = "Aseem Nishad"
subTitle = ""
blogUrl = "http://aseemnishad.com"
authorName = "Aseem Nishad"
authorBio = "Posts by <strong>Aseem Nishad</strong>, I work @<a href='https://bititude.com'>Bititude</a>. 
#Follow me on <a href='https://twitter.com/aseemnishad'>Twitter</a> &amp;
#<a href='https://github.com/aseemnishad'>Github</a>"
#linkPrefix = "aseemnishad.github.io"
# gaCode = "UA-0000000-0"
disqusShortname = "aseem"
# kommentsCode = "00000000-0000-0000-0000-000000000000"